name: REACT CI

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test with vitest and report coverage
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Install dependencies & build
        run: npm install

      - name: Test
        run: npm run coverage

      - name: Upload coverage folder
        uses: actions/upload-artifact@v6
        with:
          name: coverage-report
          path: coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: 📦Pack
        run: npm pack

      - uses: actions/upload-artifact@v6
        with:
          name: npm-package
          path: configcat-react*.tgz

  publish:
    needs: [test]
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC (see also https://docs.npmjs.com/trusted-publishers)
      contents: read
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies & build
        run: npm install

      - name: 🚀Publish
        run: npm publish
